// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    attributes: {
      name: {
        type: 'string',
        required: true
      },
      email: {
        type: 'email',
        required: true
      },
      password: {
        type: 'string',
        required: 'true'
      }
    }
  };

}).call(this);
